@GENERATED_WARNING@
FROM php:@DOCKER_FROM_TAG@

MAINTAINER Paweł Tomulik <ptomulik@@meil.pw.edu.pl>

@DOCKER_DOCTUM_ARGS@

ARG BUILD_DATE
ARG VCS_REF
ARG VERSION

LABEL org.label-schema.build-date="${BUILD_DATE}" \
      org.label-schema.name="Docker Doctum Image" \
      org.label-schema.description="Docker image with Doctum documentation generator." \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.vcs-url="https://github.com/phptailors/docker-doctum" \
      org.label-schema.vendor="Paweł Tomulik" \
      org.label-schema.version="${VERSION}" \
      org.label-schema.schema-version="1.0"


@DOCKER_DOCTUM_ENV@

RUN set -xe && \
  apk add --no-cache --update inotify-tools git && \
  curl -s -L -o /tmp/doctum.phar https://doctum.long-term.support/releases/${DOCTUM_VERSION}/doctum.phar && \
  curl -s -L -o /tmp/doctum.sha256 https://doctum.long-term.support/releases/${DOCTUM_VERSION}/doctum.phar.sha256 && \
  sha256sum -s -c -w /tmp/doctum.sha256 && \
  mv /tmp/doctum.phar /usr/local/bin/doctum && \
  rm -f /tmp/doctum.sha256 && \
  chmod +x /usr/local/bin/doctum && \
  mkdir -p "`dirname \"${DOCTUM_CONFIG}\"`"

COPY bin/* /usr/local/bin/
COPY etc/doctum.conf.php /etc/doctum/

VOLUME ${TLR_CODE}
WORKDIR ${TLR_CODE}

ENTRYPOINT [ "doctum-entrypoint" ]
CMD [ "autoserve" ]

EXPOSE ${DOCTUM_SERVER_PORT}

# vim: ft=dockerfile:
