name: Build Docker Image
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  provide_matrix_json:
    name: Provide matrix.json
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set Matrix
        id: set-matrix
        run: python3 -c 'import config; import json; print("::set-output name=matrix::" + json.dumps(config.matrix));'

      - name: Verify
        run: echo "${{ steps.set-matrix.outputs.matrix }}"

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  push_to_docker_hub:
    name: Docker Hub
    runs-on: ubuntu-latest
    needs: provide_matrix_json

    strategy:
      fail-fast: false
      matrix:
        docker_image:
          - 'phptailors/doctum'
        tuple: ${{ fromJson(needs.provide_matrix_json.outputs.matrix) }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Prepare
        id: prep
        run: |
          python3 -c 'import config; print("::set-output name=context::" + config.context_dir("${{ matrix.tuple[0] }}", "${{ matrix.tuple[1] }}"))'
          python3 -c 'import config; print("::set-output name=tag::" + config.context_tag("${{ matrix.tuple[0] }}", "${{ matrix.tuple[1] }}"))'
          python3 -c 'import config; import json; print("::set-output name=tags::" + ",".join([ "${{ matrix.docker_image }}:%s" % c for c in config.context_tags("${{ matrix.tuple[0] }}", "${{ matrix.tuple[1] }}")]))'
          echo "::set-output name=vcs_ref::$(git rev-parse --short HEAD)"
          echo "::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          python3 -c 'import config; print("::set-output name=version::" + config.__version__)'

      - name: Verify
        run: |
          echo "${{ steps.prep.outputs.tags }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'create' && github.event.ref_type == 'tag' }}
          file: ${{ steps.prep.outputs.context }}/Dockerfile
          context: ${{ steps.prep.outputs.context }}
          tags: ${{ steps.prep.outputs.tags }}
          build-args: |
            VCS_REF=${{ steps.prep.outputs.vcs_ref }}
            BUILD_DATE=${{ steps.prep.outputs.build_date }}
            VERSION=${{ steps.prep.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
