---
Retrieves a list of releases from remote repository and outputs it in JSON form
to console. Action inputs may be provided via HTML form when triggered manually.
---

name: Get & Print Releases

on:
    workflow_dispatch:
        inputs:
            owner:
                description: 'Owner'
                required: true
                default: 'code-lts'
            repo:
                description: 'Repo'
                required: true
                default: 'doctum'
            name:
                description: 'Name'
                required: false
            tag_name:
                description: 'Tag'
                required: false
                default: '/v5\.2\.\d+/'
            draft:
                description: 'Draft'
                required: false
            prerelease:
                description: 'Prerelease'
                required: false
            sort:
                description: 'Sort'
                required: false
                default: id DSC
            select:
                description: 'Select'
                required: false
                default: id, name, tag, created_at, published_at, url
            slice:
                description: 'Slice'
                required: false

jobs:
    main:
        name: Get & Print Releases
        runs-on: ubuntu-latest

        steps:

            - name: Get Releases
              id: releases
              uses: ptomulik/github-action-get-releases@v0
              with:
                  token: ${{ secrets.GET_RELEASES_TOKEN }}
                  owner: ${{ github.event.inputs.owner }}
                  repo: ${{ github.event.inputs.repo }}
                  name: ${{ github.event.inputs.name }}
                  tag_name: ${{ github.event.inputs.tag_name }}
                  draft: ${{ github.event.inputs.draft }}
                  prerelease: ${{ github.event.inputs.prerelease }}
                  sort: ${{ github.event.inputs.sort }}
                  select: ${{ github.event.inputs.select }}
                  slice: ${{ github.event.inputs.slice }}

            - name: Print Releases
              run: |
                  echo -n 'releases: ' && jq '' <<'!'
                  ${{ steps.releases.outputs.json }}
                  !
                  echo 'count: ${{ steps.releases.outputs.count }}'

# vim: set ft=yaml ts=4 sw=4 sts=4 et:
