---
name: Get & Print Releases

on:
    workflow_dispatch:
        inputs:
            owner:
                description: 'owner'
                required: true
                default: 'ptomulik'
            repo:
                description: 'repo'
                required: true
                default: 'github-list-releases-action'
            name:
                description: 'name (e.g. "Release v1.2.3")'
                required: false
            tag_name:
                description: 'tag_name (e.g. "v1.2.3")'
                required: false
                default: '/v0\.\d+.\d+/'
            draft:
                description: 'draft ("true" or "false")'
                required: false
            prerelease:
                description: 'prerelease ("true" or "false")'
                required: false
            sort:
                description: 'sort (e.g. "tag_name DSC, id DSC")'
                required: false
                default: id DSC
            select:
                description: 'select (e.g. "id, tag_name, url")'
                required: false
                default: id, name, tag_name, created_at, published_at, url
            slice:
                description: 'slice (e.g. "first 3")'
                required: false

jobs:
    main:
        name: Get & Print Releases
        runs-on: ubuntu-latest

        steps:

            - name: Get Releases
              id: releases
              uses: ptomulik/github-list-releases-action@v0
              with:
                  token: ${{ secrets.GET_RELEASES_TOKEN }}
                  owner: ${{ github.event.inputs.owner }}
                  repo: ${{ github.event.inputs.repo }}
                  name: ${{ github.event.inputs.name }}
                  tag_name: ${{ github.event.inputs.tag_name }}
                  draft: ${{ github.event.inputs.draft }}
                  prerelease: ${{ github.event.inputs.prerelease }}
                  sort: ${{ github.event.inputs.sort }}
                  select: ${{ github.event.inputs.select }}
                  slice: ${{ github.event.inputs.slice }}

            - name: Print Releases
              run: |
                  echo -n 'releases: ' && jq '' <<'!'
                  ${{ steps.releases.outputs.json }}
                  !
                  echo 'count: ${{ steps.releases.outputs.count }}'

# vim: set ft=yaml ts=4 sw=4 sts=2:
